FROM <%= base_image %>
MAINTAINER <%= author['name'] %> <%= author['email'].inspect %>

ARG luban_uid
ARG luban_user

# Add application archives
ADD <%= build[:archives].collect { |_, a| a[:path].basename }.join(" \\\n    ") %> /

# Create luban user with the given uid
RUN adduser -ms /bin/bash -u $luban_uid $luban_user && \
    echo "source <%= envrc_file %>" >> /home/$luban_user/.bashrc && \
    chown -R $luban_user:$luban_user $luban_root_path

# Populate image labels
LABEL luban.project="<%= project %>" \
      luban.application="<%= project %>" \
      luban.stage="<%= stage %>" \
      <%- build[:sources].each_pair do |name, source| -%>
      luban.<%= name %>.source_tag="<%= source[:tag] %>" \
      <%- end -%>
      luban.build_tag="<%= build_tag %>" \
      luban.bulid_rev="<%= build[:revision] %>" \
      <%- get_packages.each_pair do |name, package| -%>
      <%- package.each_pair do |k, v| -%>
      luban.packages.<%= name %>.<%= k %>="<%= v %>" \
      <%- end -%>
      <%- end -%>
      luban.luban_uid="$luban_uid" \
      luban.luban_user="$luban_user" \
      luban.luban_root_path="$luban_root_path"

USER $luban_user
WORKDIR /home/$luban_user

CMD ["/bin/bash"]
